[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "pysemtools"
version = "1.0.0"
requires-python = ">= 3.10, <3.13"
dependencies = [
    "numpy<2.0",
    "scipy",
    "pre-commit",
    "pymech",
    "mpi4py", 
    "tqdm",
    "h5py",
    "pympler", 
    "rtree",
    "pytest",
    "memory-profiler",
]

[project.optional-dependencies]
gpu = [
    "torch",
    "torchvision", 
    "torchaudio"
]
streaming = [
    "adios2"
]

[project.scripts]
pysemtools_index-files = "pysemtools.cli.index_files:main"
pysemtools_visnek = "pysemtools.cli.visnek:main"
pysemtools_extract_subdomain = "pysemtools.cli.extract_subdomain:main"